import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import type { Household, Member } from "./generator";
import { inr2, plain, dateShort, downloadBlob } from "./format";
import { CATEGORY_META, type TxnCategory } from "./data";
import { computeItr } from "./exports-doc";

export type DocId = "cibil" | "bank" | "card" | "loan" | "form16" | "itr";

export const DOC_LIST: { id: DocId; label: string; short: string }[] = [
  { id: "cibil", label: "CIBIL Report", short: "CIBIL" },
  { id: "bank", label: "Bank Statement", short: "Bank" },
  { id: "card", label: "Credit Card Statement", short: "Card" },
  { id: "loan", label: "Loan Statement", short: "Loan" },
  { id: "form16", label: "Form 16", short: "Form 16" },
  { id: "itr", label: "ITR Acknowledgement", short: "ITR" },
];

const NAVY: [number, number, number] = [14, 22, 38];
const CARD: [number, number, number] = [23, 35, 60];
const LIME: [number, number, number] = [195, 242, 77];
const FOG: [number, number, number] = [120, 136, 166];
const INKP: [number, number, number] = [28, 36, 56];

const safeName = (m: Member) => m.name.replace(/\s+/g, "");

function docAvailable(doc: DocId, m: Member): boolean {
  switch (doc) {
    case "cibil": return m.age >= 18;
    case "bank": return true;
    case "card": return !!m.card;
    case "loan": return !!m.loan;
    case "form16": return m.employment.kind === "salaried";
    case "itr": return m.age >= 18 && m.employment.monthlyGross > 0;
  }
}
export { docAvailable };

/* --------------------------------- PDF --------------------------------- */

type Pdf = jsPDF;

function pdfHeader(doc: Pdf, title: string, subtitle: string, right: string) {
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, 595, 78, "F");
  doc.setFillColor(...LIME);
  doc.rect(0, 78, 595, 3, "F");
  doc.setTextColor(242, 246, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.text(title, 36, 36);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(...FOG);
  doc.text(subtitle, 36, 54);
  doc.setTextColor(...LIME);
  doc.setFontSize(8);
  doc.text(right, 559, 36, { align: "right" });
  doc.setTextColor(...FOG);
  doc.text("SYNTHETIC DATA — NOT REAL", 559, 50, { align: "right" });
  return 100;
}

function pdfMeta(doc: Pdf, rows: [string, string][], yStart?: number, cols = 2): number {
  const y =
    yStart ??
    ((doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 84) + 18;
  const colW = (595 - 72) / cols;
  doc.setFontSize(9);
  rows.forEach((r, i) => {
    const cx = 36 + (i % cols) * colW;
    const cy = y + Math.floor(i / cols) * 34;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...FOG);
    doc.text(r[0].toUpperCase(), cx, cy);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...INKP);
    doc.setFontSize(10.5);
    doc.text(r[1], cx, cy + 14);
    doc.setFontSize(9);
  });
  return y + Math.ceil(rows.length / cols) * 34 + 6;
}

function pdfTable(doc: Pdf, head: string[], body: (string | number)[][], opts?: { right?: number[]; startY?: number }) {
  const lastY = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY;
  autoTable(doc, {
    head: [head],
    body,
    startY: opts?.startY ?? (lastY ? lastY + 12 : 100),
    margin: { left: 36, right: 36 },
    styles: { font: "helvetica", fontSize: 8.2, cellPadding: 4.5, textColor: [40, 48, 66] },
    headStyles: { fillColor: NAVY, textColor: [242, 246, 255], fontStyle: "bold" },
    alternateRowStyles: { fillColor: [244, 247, 252] },
    columnStyles: Object.fromEntries((opts?.right ?? []).map((c) => [c, { halign: "right" as const }])),
  });
}

function pdfFooter(doc: Pdf) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(7.5);
    doc.setTextColor(...FOG);
    doc.text(`Generated by DhanForge · Synthetic household data for testing · Page ${i} of ${pages}`, 297.5, 822, { align: "center" });
  }
}

function bandLabel(score: number): string {
  return score >= 750 ? "Excellent" : score >= 700 ? "Good" : score >= 650 ? "Fair" : "Poor";
}



function buildPDF(doc: DocId, hh: Household, m: Member) {
  const pdf = new jsPDF({ unit: "pt", format: "a4" });
  const who = `${m.name} · ${hh.familyName} household, ${hh.city.name}`;

  if (doc === "cibil" && m.cibil != null) {
    let y = pdfHeader(pdf, "CIBIL Credit Report", who, `Score ${m.cibil}`);
    pdf.setFillColor(...CARD);
    pdf.roundedRect(36, y, 523, 64, 10, 10, "F");
    pdf.setTextColor(...LIME);
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(30);
    pdf.text(`${m.cibil}`, 56, y + 44);
    pdf.setFontSize(10);
    pdf.setTextColor(242, 246, 255);
    pdf.text(`Rating: ${bandLabel(m.cibil)}  ·  Range 300–900`, 120, y + 38);
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(8.5);
    pdf.setTextColor(...FOG);
    pdf.text("Score derived from 36 months of synthetic repayment behaviour.", 120, y + 52);
    pdfTable(pdf, ["Factor", "Status", "Impact"], [
      ["Payment History", m.cibil >= 700 ? "Excellent — 0 missed EMIs" : "Good — 1 late mark", m.cibil >= 700 ? "Positive" : "Neutral"],
      ["Credit Utilisation", m.card ? `${Math.round((m.card.lastStatementTotal / m.card.limit) * 100)}% of limit` : "No revolving credit", m.card && m.card.lastStatementTotal / m.card.limit < 0.35 ? "Positive" : "Negative"],
      ["Credit Age", `${Math.max(1, Math.min(14, m.age - 21))}+ years`, "Positive"],
      ["Credit Mix", m.loan && m.card ? "Secured + revolving" : "Single type", m.loan && m.card ? "Positive" : "Neutral"],
      ["Recent Enquiries", `${m.age % 3} in last 6 months`, m.age % 3 === 0 ? "Positive" : "Neutral"],
    ], { startY: y + 84 });
    pdfTable(pdf, ["Account", "Institution", "Type", "Amount", "Status", "Open Since"],
      m.tradelines.map((t) => [t.account, t.institution, t.type, inr2(t.amount), t.status, dateShort(t.since)]),
      { right: [3] });
    pdfFooter(pdf);
  }

  if (doc === "bank") {
    const first = m.txns[0];
    const last = m.txns[m.txns.length - 1];
    const opening = first ? first.balance - first.amount : m.openingBalance;
    let y = pdfHeader(pdf, `${m.bankName} — Bank Statement`, who, `A/c ••••${m.accountNo.slice(-4)}`);
    y = pdfMeta(pdf, [
      ["Account Holder", m.name], ["Account Number", m.accountNo],
      ["IFSC", m.ifsc], ["Branch", m.branch],
      ["Statement Period", first && last ? `${dateShort(first.date)} – ${dateShort(last.date)}` : "—"],
      ["Opening Balance", inr2(opening)],
    ]);
    const rows = m.txns.map((t) => [
      dateShort(t.date), t.narration, t.ref,
      t.amount < 0 ? plain(-t.amount) : "", t.amount > 0 ? plain(t.amount) : "", plain(t.balance),
    ]);
    pdfTable(pdf, ["Date", "Narration", "Reference", "Debit (₹)", "Credit (₹)", "Balance (₹)"], rows, { right: [3, 4, 5], startY: y });
    const cr = m.txns.filter((t) => t.amount > 0).reduce((s, t) => s + t.amount, 0);
    const dr = m.txns.filter((t) => t.amount < 0).reduce((s, t) => s - t.amount, 0);
    pdf.setFontSize(9);
    pdf.setTextColor(...INKP);
    pdf.setFont("helvetica", "bold");
    const fy = (pdf as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y;
    pdf.text(`Total Credits: ${inr2(cr)}    Total Debits: ${inr2(dr)}    Closing Balance: ${inr2(last?.balance ?? opening)}`, 36, fy + 18);
    pdfFooter(pdf);
  }

  if (doc === "card" && m.card) {
    const key = stmtMonthKey();
    const period = m.card.txns.filter((t) => t.date.startsWith(key));
    const purchases = period.reduce((s, t) => s + t.amount, 0);
    let y = pdfHeader(pdf, `${m.card.bank} — Credit Card Statement`, who, m.card.product);
    y = pdfMeta(pdf, [
      ["Card Number", m.card.numberMasked], ["Credit Limit", inr2(m.card.limit)],
      ["Statement Cycle", stmtMonthLabel()], ["Payment Due Date", dueDateLabel()],
      ["Total Amount Due", inr2(purchases)], ["Minimum Amount Due", inr2(Math.round(purchases * 0.05))],
    ]);
    pdfTable(pdf, ["Date", "Particulars", "Amount (₹)"],
      period.map((t) => [dateShort(t.date), t.detail, plain(t.amount)]), { right: [2], startY: y });
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(...INKP);
    const fy = (pdf as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y;
    pdf.text(`Opening Balance: ₹0.00 (paid in full) · Finance Charge: ₹0.00 · Reward Points Earned: ${Math.round(purchases / 100)}`, 36, fy + 18);
    pdfFooter(pdf);
  }

  if (doc === "loan" && m.loan) {
    let y = pdfHeader(pdf, `${m.loan.lender} — Loan Statement`, who, m.loan.type);
    y = pdfMeta(pdf, [
      ["Loan Account", m.loan.accountNo], ["Sanction Date", dateShort(m.loan.sanctionDate)],
      ["Principal Amount", inr2(m.loan.principal)], ["Interest Rate", `${m.loan.rate}% p.a.`],
      ["Tenure", `${m.loan.tenureMonths} months`], ["Monthly EMI", inr2(m.loan.emi)],
      ["Installments Paid", `${m.loan.paidInstallments} of ${m.loan.tenureMonths}`],
      ["Outstanding Principal", inr2(m.loan.outstanding)],
    ]);
    pdfTable(pdf, ["#", "Due Date", "EMI (₹)", "Principal (₹)", "Interest (₹)", "Balance (₹)"],
      m.loan.schedule.map((s) => [s.no, dateShort(s.date), plain(s.emi), plain(s.principal), plain(s.interest), plain(s.balance)]),
      { right: [2, 3, 4, 5], startY: y });
    pdfFooter(pdf);
  }

  if (doc === "form16" && m.form16) {
    const f = m.form16;
    let y = pdfHeader(pdf, "Form 16 — TDS Certificate", `${who} · ${f.fy} · ${f.ay}`, `PAN ${m.pan}`);
    y = pdfMeta(pdf, [
      ["Employer", f.employer], ["Employer TAN", f.tan],
      ["Employee", m.name], ["Employee PAN", m.pan ?? "—"],
      ["Assessment Year", f.ay], ["Gross Salary", inr2(f.gross)],
    ]);
    pdfTable(pdf, ["Part B — Income & Deductions", "Amount (₹)"], [
      ["Gross Salary (u/s 17(1))", plain(f.gross)],
      ["  — Basic", plain(f.basic)], ["  — House Rent Allowance", plain(f.hra)], ["  — Special Allowance", plain(f.special)],
      ["Less: Standard Deduction (u/s 16(ia))", `(${plain(f.stdDeduction)})`],
      ["Less: HRA Exempt (u/s 10(13A))", `(${plain(f.hraExempt)})`],
      ["Less: Employee EPF Contribution", `(${plain(f.epfEmployee)})`],
      ["Less: Deduction u/s 80C", `(${plain(f.c80)})`],
      ["Less: Deduction u/s 80D", `(${plain(f.d80)})`],
      ["Income from Other Sources", plain(f.otherIncome)],
      ["Net Taxable Income", plain(f.taxable)],
      ["Income Tax", plain(f.tax)], ["Health & Education Cess (4%)", plain(f.cess)],
      ["Total Tax Deducted at Source", plain(f.totalTax)],
      ["Average Monthly TDS", plain(f.tdsMonthly)],
    ], { right: [1], startY: y });
    pdfFooter(pdf);
  }

  if (doc === "itr") {
    const t = computeItr(m);
    let y = pdfHeader(pdf, "ITR-1 (Sahaj) — Acknowledgement", `${who} · ${t.ay}`, `ACK ${t.ack}`);
    y = pdfMeta(pdf, [
      ["PAN", m.pan ?? "—"], ["Assessment Year", t.ay],
      ["Return Form", "ITR-1 (Sahaj)"], ["Filing Mode", "e-Filed with Aadhaar OTP"],
      ["Filing Date", dateShort(new Date().toISOString())], ["Acknowledgement No.", t.ack],
    ]);
    pdfTable(pdf, ["Computation", "Amount (₹)"], [
      ["Gross Total Income", plain(t.grossTotal)],
      ["Total Deductions (Ch. VI-A & others)", `(${plain(t.deductions)})`],
      ["Total Income", plain(t.totalIncome)],
      ["Tax Liability (incl. cess)", plain(t.taxLiability)],
      ["TDS / Taxes Paid", plain(t.tds)],
      t.refund > 0 ? ["Refund Issuable", plain(t.refund)] : ["Tax Payable (Self-Assessment)", plain(t.payable)],
    ], { right: [1], startY: y });
    pdfFooter(pdf);
  }

  pdf.save(`DhanForge_${safeName(m)}_${doc.toUpperCase()}.pdf`);
}

function stmtMonthKey(): string {
  const now = new Date();
  const d = new Date(now.getFullYear(), now.getMonth() - 1, 1);
  return `${d.getFullYear()}-${`${d.getMonth() + 1}`.padStart(2, "0")}`;
}
function stmtMonthLabel(): string {
  const now = new Date();
  const d = new Date(now.getFullYear(), now.getMonth() - 1, 1);
  return d.toLocaleDateString("en-IN", { month: "long", year: "numeric" });
}
function dueDateLabel(): string {
  const now = new Date();
  return new Date(now.getFullYear(), now.getMonth(), 18).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
}

/* --------------------------------- XLSX --------------------------------- */

function sheetFromAOA(name: string, aoa: (string | number)[][]) {
  const ws = XLSX.utils.aoa_to_sheet(aoa);
  ws["!cols"] = aoa[0]?.map((_, c) => ({
    wch: Math.max(12, ...aoa.map((r) => `${r[c] ?? ""}`.length + 2)),
  }));
  return { name: name.slice(0, 31), ws };
}

function memberSheets(hh: Household, m: Member) {
  const sheets: { name: string; ws: XLSX.WorkSheet }[] = [];
  const fn = `${safeName(m).slice(0, 9)}${m.id.replace("m", "")}`;

  sheets.push(sheetFromAOA(`${fn}-Bank`, [
    [`${m.bankName} — Bank Statement`], [m.name], [`A/c ${m.accountNo}`, `IFSC ${m.ifsc}`, m.branch],
    ["Date", "Narration", "Reference", "Debit", "Credit", "Balance"],
    ...m.txns.map((t) => [dateShort(t.date), t.narration, t.ref, t.amount < 0 ? -t.amount : 0, t.amount > 0 ? t.amount : 0, t.balance]),
  ]));

  if (m.card) {
    const period = m.card.txns.filter((t) => t.date.startsWith(stmtMonthKey()));
    sheets.push(sheetFromAOA(`${fn}-Card`, [
      [`${m.card.product} — Credit Card Statement`], [m.card.numberMasked], [`Limit ${m.card.limit}`, stmtMonthLabel()],
      ["Date", "Particulars", "Category", "Amount"],
      ...period.map((t) => [dateShort(t.date), t.detail, CATEGORY_META[t.category as TxnCategory].label, t.amount]),
      [], ["Total Purchases", period.reduce((s, t) => s + t.amount, 0)], ["Minimum Due", Math.round(period.reduce((s, t) => s + t.amount, 0) * 0.05)],
    ]));
  }

  if (m.loan) {
    sheets.push(sheetFromAOA(`${fn}-Loan`, [
      [`${m.loan.type} — ${m.loan.lender}`], [`A/c ${m.loan.accountNo}`, `${m.loan.rate}% p.a.`, `${m.loan.tenureMonths} months`],
      ["#", "Due Date", "EMI", "Principal", "Interest", "Balance"],
      ...m.loan.schedule.map((s) => [s.no, dateShort(s.date), s.emi, s.principal, s.interest, s.balance]),
    ]));
  }

  if (m.form16) {
    const f = m.form16;
    sheets.push(sheetFromAOA(`${fn}-Form16`, [
      [`Form 16 — ${f.ay}`], [f.employer, `TAN ${f.tan}`], [m.name, `PAN ${m.pan}`],
      ["Head", "Amount"],
      ["Gross Salary", f.gross], ["Basic", f.basic], ["HRA", f.hra], ["Special", f.special],
      ["Standard Deduction", -f.stdDeduction], ["HRA Exempt", -f.hraExempt], ["EPF (employee)", -f.epfEmployee],
      ["80C", -f.c80], ["80D", -f.d80], ["Other Income", f.otherIncome], ["Taxable Income", f.taxable],
      ["Income Tax", f.tax], ["Cess", f.cess], ["Total TDS", f.totalTax],
    ]));
  }

  if (m.age >= 18 && m.employment.monthlyGross > 0) {
    const t = computeItr(m);
    sheets.push(sheetFromAOA(`${fn}-ITR`, [
      [`ITR-1 Acknowledgement — ${t.ay}`], [m.name, `PAN ${m.pan}`, `ACK ${t.ack}`],
      ["Head", "Amount"],
      ["Gross Total Income", t.grossTotal], ["Deductions", -t.deductions], ["Total Income", t.totalIncome],
      ["Tax Liability", t.taxLiability], ["TDS", t.tds], ["Refund", t.refund], ["Payable", t.payable],
    ]));
  }

  if (m.age >= 18) {
    sheets.push(sheetFromAOA(`${fn}-CIBIL`, [
      [`CIBIL Report — ${m.name}`], ["Score", m.cibil ?? "NH (No History)"],
      ["Account", "Institution", "Type", "Amount", "Status", "Since"],
      ...m.tradelines.map((t) => [t.account, t.institution, t.type, t.amount, t.status, dateShort(t.since)]),
    ]));
  }
  return sheets;
}

function buildMemberXLSX(hh: Household, m: Member) {
  const wb = XLSX.utils.book_new();
  memberSheets(hh, m).forEach((s) => XLSX.utils.book_append_sheet(wb, s.ws, s.name));
  XLSX.writeFile(wb, `DhanForge_${safeName(m)}_AllDocs.xlsx`);
}

function buildHouseholdXLSX(hh: Household) {
  const wb = XLSX.utils.book_new();
  const roster = sheetFromAOA("Household", [
    [`DhanForge — ${hh.familyName} Household (${hh.city.name})`],
    [`Monthly Income ${hh.monthlyIncome} · Monthly Expense ${hh.monthlyExpense} · EMIs ${hh.monthlyEmi} · Net ${hh.net}`],
    ["Name", "Age", "Gender", "Role", "Occupation", "Employer", "Monthly Income", "CIBIL", "Bank", "PAN"],
    ...hh.members.map((m) => [
      m.name, m.age, m.gender, m.role, m.employment.title, m.employment.employer ?? "—",
      m.employment.monthlyTakeHome, m.cibil ?? "NH", m.bankName, m.pan ?? "—",
    ]),
  ]);
  XLSX.utils.book_append_sheet(wb, roster.ws, roster.name);
  hh.members.forEach((m) => memberSheets(hh, m).forEach((s) => XLSX.utils.book_append_sheet(wb, s.ws, s.name)));
  XLSX.writeFile(wb, `DhanForge_${hh.familyName}_Household.xlsx`);
}

/* ---------------------------------- DOC ---------------------------------- */

function docHTML(title: string, meta: [string, string][], tables: { head: string[]; rows: (string | number)[][] }[], notes: string[] = []): string {
  const metaRows = meta.map(([k, v]) => `<tr><td class="k">${k}</td><td>${v}</td></tr>`).join("");
  const tbls = tables.map(
    (t) => `<table><thead><tr>${t.head.map((h) => `<th>${h}</th>`).join("")}</tr></thead><tbody>${t.rows
      .map((r) => `<tr>${r.map((c) => `<td>${c}</td>`).join("")}</tr>`).join("")}</tbody></table>`,
  ).join("");
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${title}</title><style>
body{font-family:'Segoe UI',Arial,sans-serif;color:#1c2438;max-width:860px;margin:24px auto;padding:0 16px}
h1{font-size:20px;margin:0 0 2px}
.sub{color:#66708a;font-size:11px;margin-bottom:16px}
.badge{display:inline-block;background:#eafad0;color:#3d5a00;font-size:10px;padding:2px 8px;border-radius:99px;margin-left:8px}
table.meta{border-collapse:collapse;margin:14px 0}
table.meta td{padding:6px 18px 6px 0;font-size:12px;vertical-align:top}
table.meta td.k{color:#66708a;font-weight:600;min-width:150px}
table{border-collapse:collapse;width:100%;margin:14px 0;font-size:11px}
th{background:#0e1626;color:#f2f6ff;padding:7px 9px;text-align:left;font-weight:600}
td{border:1px solid #d7deec;padding:6px 9px}
tr:nth-child(even) td{background:#f4f7fc}
.note{color:#66708a;font-size:10px;margin-top:18px;border-top:1px solid #d7deec;padding-top:8px}
</style></head><body>
<h1>${title}<span class="badge">SYNTHETIC DATA</span></h1>
<div class="sub">Generated by DhanForge · Synthetic household data for testing · ${new Date().toLocaleDateString("en-IN")}</div>
<table class="meta">${metaRows}</table>${tbls}
${notes.map((n) => `<div class="note">${n}</div>`).join("")}
</body></html>`;
}

function buildDOC(doc: DocId, hh: Household, m: Member) {
  const who = `${m.name} · ${hh.familyName} household, ${hh.city.name}`;
  let html = "";

  if (doc === "cibil" && m.cibil != null) {
    html = docHTML(`CIBIL Credit Report — ${who}`, [
      ["CIBIL Score", `${m.cibil} (${bandLabel(m.cibil)})`], ["Score Range", "300–900"], ["PAN", m.pan ?? "—"],
    ], [{
      head: ["Account", "Institution", "Type", "Amount", "Status", "Open Since"],
      rows: m.tradelines.map((t) => [t.account, t.institution, t.type, inr2(t.amount), t.status, dateShort(t.since)]),
    }], ["Factors: payment history, utilisation, credit age, credit mix and enquiries are derived from synthetic behaviour."]);
  }
  if (doc === "bank") {
    const last = m.txns[m.txns.length - 1];
    const first = m.txns[0];
    html = docHTML(`${m.bankName} — Bank Statement`, [
      ["Account Holder", m.name], ["Account Number", m.accountNo], ["IFSC", m.ifsc], ["Branch", m.branch],
      ["Period", first && last ? `${dateShort(first.date)} – ${dateShort(last.date)}` : "—"],
      ["Closing Balance", last ? inr2(last.balance) : "—"],
    ], [{
      head: ["Date", "Narration", "Reference", "Debit", "Credit", "Balance"],
      rows: m.txns.map((t) => [dateShort(t.date), t.narration, t.ref, t.amount < 0 ? inr2(-t.amount) : "", t.amount > 0 ? inr2(t.amount) : "", inr2(t.balance)]),
    }]);
  }
  if (doc === "card" && m.card) {
    const period = m.card.txns.filter((t) => t.date.startsWith(stmtMonthKey()));
    const purchases = period.reduce((s, t) => s + t.amount, 0);
    html = docHTML(`${m.card.bank} — Credit Card Statement`, [
      ["Card", `${m.card.product} · ${m.card.numberMasked}`], ["Credit Limit", inr2(m.card.limit)],
      ["Statement Cycle", stmtMonthLabel()], ["Payment Due", dueDateLabel()],
      ["Total Amount Due", inr2(purchases)], ["Minimum Amount Due", inr2(Math.round(purchases * 0.05))],
    ], [{
      head: ["Date", "Particulars", "Amount"],
      rows: period.map((t) => [dateShort(t.date), t.detail, inr2(t.amount)]),
    }], [`Reward points earned this cycle: ${Math.round(purchases / 100)}`]);
  }
  if (doc === "loan" && m.loan) {
    html = docHTML(`${m.loan.lender} — ${m.loan.type} Statement`, [
      ["Loan Account", m.loan.accountNo], ["Sanction Date", dateShort(m.loan.sanctionDate)],
      ["Principal", inr2(m.loan.principal)], ["Rate", `${m.loan.rate}% p.a.`], ["Tenure", `${m.loan.tenureMonths} months`],
      ["EMI", inr2(m.loan.emi)], ["Outstanding", inr2(m.loan.outstanding)], ["Next Due", dateShort(m.loan.nextDue)],
    ], [{
      head: ["#", "Due Date", "EMI", "Principal", "Interest", "Balance"],
      rows: m.loan.schedule.map((s) => [s.no, dateShort(s.date), inr2(s.emi), inr2(s.principal), inr2(s.interest), inr2(s.balance)]),
    }]);
  }
  if (doc === "form16" && m.form16) {
    const f = m.form16;
    html = docHTML(`Form 16 — ${f.ay}`, [
      ["Employer", f.employer], ["Employer TAN", f.tan], ["Employee", m.name], ["Employee PAN", m.pan ?? "—"],
      ["Financial Year", f.fy], ["Assessment Year", f.ay],
    ], [{
      head: ["Part B — Computation", "Amount"],
      rows: [
        ["Gross Salary", inr2(f.gross)], ["Basic", inr2(f.basic)], ["HRA", inr2(f.hra)], ["Special Allowance", inr2(f.special)],
        ["Standard Deduction u/s 16(ia)", `(${inr2(f.stdDeduction)})`], ["HRA Exempt u/s 10(13A)", `(${inr2(f.hraExempt)})`],
        ["EPF (employee share)", `(${inr2(f.epfEmployee)})`], ["Deduction u/s 80C", `(${inr2(f.c80)})`],
        ["Deduction u/s 80D", `(${inr2(f.d80)})`], ["Income from Other Sources", inr2(f.otherIncome)],
        ["Net Taxable Income", inr2(f.taxable)], ["Income Tax", inr2(f.tax)], ["Cess @4%", inr2(f.cess)],
        ["Total TDS", inr2(f.totalTax)],
      ],
    }]);
  }
  if (doc === "itr") {
    const t = computeItr(m);
    html = docHTML(`ITR-1 (Sahaj) Acknowledgement — ${t.ay}`, [
      ["Name", m.name], ["PAN", m.pan ?? "—"], ["Assessment Year", t.ay],
      ["Acknowledgement No.", t.ack], ["Filing Date", dateShort(new Date().toISOString())],
    ], [{
      head: ["Computation", "Amount"],
      rows: [
        ["Gross Total Income", inr2(t.grossTotal)], ["Deductions", `(${inr2(t.deductions)})`], ["Total Income", inr2(t.totalIncome)],
        ["Tax Liability", inr2(t.taxLiability)], ["TDS / Taxes Paid", inr2(t.tds)],
        t.refund > 0 ? ["Refund Issuable", inr2(t.refund)] : ["Tax Payable", inr2(t.payable)],
      ],
    }]);
  }

  downloadBlob(html, `DhanForge_${safeName(m)}_${doc.toUpperCase()}.doc`, "application/msword");
}

/* --------------------------------- facade --------------------------------- */

export function exportDoc(kind: "pdf" | "xlsx" | "doc", doc: DocId, hh: Household, m: Member) {
  if (!docAvailable(doc, m)) {
    throw new Error(`${doc} is not available for ${m.name}`);
  }
  if (kind === "pdf") buildPDF(doc, hh, m);
  else if (kind === "xlsx") buildMemberXLSX(hh, m);
  else buildDOC(doc, hh, m);
}

export function exportAllXLSX(hh: Household) {
  buildHouseholdXLSX(hh);
}
